### ISSUE TITLE
string with $ error

### ISSUE THREAD

**Issue by ghost** [void-stack/VMUnprotect#1]
I am using vs 2012 and source contains $
so

how can I fix that?

![Screenshot_129](https://user-images.githubusercontent.com/56601492/142719759-a49ae05b-a702-4ed2-b9dc-0f8faa3025b8.png)

**Comment by void-stack** [comment]
Hello, I highly recommend updating your environment since this was introduced in C# 6. http://redspa.uk/blog/post/1029/interpolated-strings-c-sharp

**Comment by ghost** [comment]
> Hello, I highly recommend updating your environment since this was introduced in C# 6. http://redspa.uk/blog/post/1029/interpolated-strings-c-sharp

I cannot use c# 6.0 due my visual studio version max 5.0
is there anyway to download this version?

**Comment by ghost** [comment]
Nope fixed with string.Format
and can you share a release?

**Comment by void-stack** [comment]
I'm going to add a release once I'm happy with the basic features and compatibility. Now I'm planning minor changes to the code to make it more reliable to others. I'll compose a TODO list soon.
